### ISSUE TITLE
TypeError: Cannot read property 'uploadSequenceToken' of undefined

### ISSUE THREAD

**Issue by bburket** [lazywithclass/winston-cloudwatch#11]
/home/bill/Documents/git/key-service-node/node_modules/aws-sdk/lib/request.js:32
          throw err;

at Response.<anonymous> (/home/bill/Documents/git/key-service-node/node_modules/winston-cloudwatch/lib/cloudwatch-integration.js:64:22)
    at Request.AWS.Request.inherit.send (/home/bill/Documents/git/key-service-node/node_modules/aws-sdk/lib/request.js:350:18)
...

**Comment by theRealGabacho** [comment]
Turns out this was caused by the log stream not yet existing.

**Comment by lazywithclass** [comment]
Thanks, I will handle that scenario so that the error is meaningful.

Possibly checking the error that I get from AWS or doing a call to see if both log group and log stream are there.
