### ISSUE TITLE
Timeout reached while waiting for logs to submit

### ISSUE THREAD

**Issue by terrisgit** [lazywithclass/winston-cloudwatch#128]
I'm waiting for kthxbye to finish and am getting a "Timeout reached while waiting for logs to submit" after about 10 seconds. Is there a way to control this timeout?

Thank you!

```
error:┏ Timeout reached while waiting for logs to submit +11s
error:┃ [ 1] Error: Timeout reached while waiting for logs to submit
error:┃ [ 2]     at WinstonCloudWatch.<anonymous> (/Users/terris/science37/nora-ehr-download/node_modules/winston-cloudwatch/index.js:143:57)
error:┃ [ 3]     at /Users/terris/science37/nora-ehr-download/node_modules/winston-cloudwatch/lib/cloudwatch-integration.js:27:12
error:┃ [ 4]     at Response.<anonymous> (/Users/terris/science37/nora-ehr-download/node_modules/winston-cloudwatch/lib/cloudwatch-integration.js:93:11)
error:┃ [ 5]     at Request.<anonymous> (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/request.js:364:18)
error:┃ [ 6]     at Request.callListeners (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
error:┃ [ 7]     at Request.emit (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
error:┃ [ 8]     at Request.emit (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/request.js:683:14)
error:┃ [ 9]     at Request.transition (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/request.js:22:10)
error:┃ [10]     at AcceptorStateMachine.runTo (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/state_machine.js:14:12)
error:┃ [11]     at /Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/state_machine.js:26:10
error:┃ [12]     at Request.<anonymous> (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/request.js:38:9)
error:┃ [13]     at Request.<anonymous> (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/request.js:685:12)
error:┃ [14]     at Request.callListeners (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
error:┃ [15]     at Request.emit (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
error:┃ [16]     at Request.emit (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/request.js:683:14)
error:┃ [17]     at Request.transition (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/request.js:22:10)
error:┃ [18]     at AcceptorStateMachine.runTo (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/state_machine.js:14:12)
error:┃ [19]     at /Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/state_machine.js:26:10
error:┃ [20]     at Request.<anonymous> (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/request.js:38:9)
error:┃ [21]     at Request.<anonymous> (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/request.js:685:12)
error:┃ [22]     at Request.callListeners (/Users/terris/science37/nora-ehr-download/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

**Comment by avnerenv0** [comment]
No, right now `defaultFlushTimeoutMs` is hard coded in `index.js`. 
We can open a PR to specify a different number through options or env var

**Comment by terrisgit** [comment]
For now, I can set flushTimeout before calling kthxbye to Date.now()+_desired timeout_

**Comment by lazywithclass** [comment]
Yes that would be the use @terrisgit.

I will close this for now, but if you'd like this feature feel free to submit a PR or offer a few tests.
