### ISSUE TITLE
In the event of an "Invalid Sequence Number error" 

### ISSUE THREAD

**Issue by lazywithclass** [lazywithclass/winston-cloudwatch#46]
Describe the logs again to get a fresh sequence number

See https://github.com/lazywithclass/winston-cloudwatch/issues/42

**Comment by twk-b** [comment]
We are starting to see the following regularly now:

{ InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: SUPERTOKEN
    at Request.extractError (/var/app/current/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/app/current/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/var/app/current/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/app/current/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/app/current/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/app/current/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/var/app/current/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/app/current/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/app/current/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'The given sequenceToken is invalid. The next expected sequenceToken is

we use the same stream between a number of instances/services....

currently this crashes our node instances. this is happening after the server has been running a while, completing putLogEvent I believe.

handling with a retry or 3 would be ideal... 

option for logging not to take down the server? winston.exitOnError: true I believe would ignore all errors, not just from logging.. exitOnLoggingError: true by default?

**Comment by lazywithclass** [comment]
Which version are you using? I think we [solved this problem a while ago](https://github.com/lazywithclass/winston-cloudwatch/blob/a5a66b2b5625dd7fd3505175a91275bb3a0806dd/lib/cloudwatch-integration.js#L77), thanks to `submitWithAnotherToken`, which has been in winston-cloudwatch since [1.11.0](https://github.com/lazywithclass/winston-cloudwatch/blob/08e0d830138b1ffefdba08f29706a7b4605d9dee/CHANGELOG.md#1110).

Please let me know.

> we use the same stream between a number of instances/services....

You might want to have 1 stream for 1 resource, that's the intended use of the service and the library. I am not saying that this error happens only because of that though. :)

**Comment by twk-b** [comment]
npm ls winston-cloudwatch

`-- winston-cloudwatch@1.11.3

**Comment by lazywithclass** [comment]
Then the problem is in the fact that your stream is shared between instances, adding a 3 times retry would just make the problem appear less often, but eventually it would still happen, because, from a single instance, as far as winston-cloudwatch is concerned, you can't understand if there's a call going on from another instance.

About your servers crashing, [1.6.0](https://github.com/lazywithclass/winston-cloudwatch/blob/08e0d830138b1ffefdba08f29706a7b4605d9dee/CHANGELOG.md#160) allows you to specify a handler and [treat uncaught exceptions](https://github.com/winstonjs/winston#handling-uncaught-exceptions-with-winston).

**Comment by twk-b** [comment]
Agreed, after talking to AWS Support, we have updated the code to setup one
stream per resource instead. In my case I was new to CloudWatch... might
make sense to spell that out in the first couple paragraphs so people new
to both winston-cloudwatch and cloudwatch get it right out of the gate.

**Comment by lazywithclass** [comment]
Glad it was resolved, thanks for the suggestion, I've [added it to the README](https://github.com/lazywithclass/winston-cloudwatch/blob/master/README.md#configuring).
