### ISSUE TITLE
InvalidAction: The action or operation requested is invalid. Verify that the action is typed correctly.

### ISSUE THREAD

**Issue by rettgerst** [lazywithclass/winston-cloudwatch#67]
I'm not sure if this is an issue with your module, but I'm running into an issue trying to integrate it into my project.

my code is basically as simple as possible:

```js
var config = require('../config.js');
var winston = require('winston'),
    WinstonCloudWatch = require('winston-cloudwatch');

winston.add(WinstonCloudWatch, config.winston);

winston.log('info', 'Did someone say peanut butter?');
```

where config.winston looks like:

```js
winston: {
    awsRegion: 'us-east-1',
    logGroupName: 'foo',
    logStreamName: 'bar'
}
```

I have verified that the group and stream exist.

running with the debug flag set to true, I get log output like:

```
DEBUG: token not found { InvalidAction: The action or operation requested is invalid. Verify that the action is typed correctly.
    at Request.extractError ([project root]/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners ([project root]/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit ([project root]/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit ([project root]/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition ([project root]/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo ([project root]/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at [project root]/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> ([project root]/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> ([project root]/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners ([project root]/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit ([project root]/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit ([project root]/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition ([project root]/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo ([project root]/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at [project root]/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> ([project root]/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'The action or operation requested is invalid. Verify that the action is typed correctly.',
  code: 'InvalidAction',
  time: 2017-08-30T19:27:37.021Z,
  requestId: 'ed40ff8b-864e-4fb7-8514-bcc37ef2aa4a',
  statusCode: 400,
  retryable: false,
  retryDelay: 95.8532443992095 }
```

after some digging, it seems like this is being returned from the describeLogStreams method [here](https://github.com/lazywithclass/winston-cloudwatch/blob/a5a66b2b5625dd7fd3505175a91275bb3a0806dd/lib/cloudwatch-integration.js#L135).

**Comment by rettgerst** [comment]
I found the root of the problem. it was a configuration issue on our part.

it turns out, somewhere else in our app, the endpoint for the AWS sdk was being set to a port on localhost, to be used with a locally running copy of dynamodb. since this configuration was being set on the root AWS object, winston-cloudwatch's internal cloudwatch service object was inheriting this configuration.

**Comment by lazywithclass** [comment]
Cool that you solved it :+1:
