### ISSUE TITLE
Rate exceeded question

### ISSUE THREAD

**Issue by dnewman-polar3d** [lazywithclass/winston-cloudwatch#69]
winston: 2.3.0
winston-cloudwatch: 1.11.4

Been using winston-cloudwatch for close to a year.  Thanks much!  But I have a question for you all.

A server of mine racks up around 800 - 900 Rate Exceeded warnings per day.   I'm trying to understand what limit exactly in CloudWatch it might be hitting (and then what to do about it).  In this usage of CloudWatch, there is only a single process logging to the CloudWatch stream and, being Node.js, it's single threaded.  When I look at [CloudWatch limits](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html) nothing jumps out at me as the obvious limit being hit.  Or is it simply too many logging calls per second my code is making?

Here's an example of the event thrown:

    Cloudwatch logging error: Rate exceeded
    { ThrottlingException: Rate exceeded
        at Request.extractError (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/protocol/json.js:48:27)
        at Request.callListeners (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
        at Request.emit (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
        at Request.emit (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/request.js:683:14)
        at Request.transition (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/request.js:38:9)
        at Request.<anonymous> (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/request.js:685:12)
        at Request.callListeners (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/sequential_executor.js :115:18)
        at Request.emit (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
        at Request.emit (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/request.js:683:14)
        at Request.transition (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/request.js:38:9)
        at Request.<anonymous> (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/request.js:685:12)
        at Request.callListeners (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
        at callNextListener (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
        at IncomingMessage.onEnd (/home/ec2-user/yunshiquan/node_modules/winston-cloudwatch/node_modules/aws-sdk/lib/event_listeners.js:269:13)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)
      message: 'Rate exceeded',
      code: 'ThrottlingException',
      time: 2017-09-25T04:03:23.285Z,
      requestId: '797c6ce8-a1a6-11e7-bd75-8138eafb0e10',
      statusCode: 400,
      retryable: true }

And, FWIW, here's the invocation of the winston-cloudwatch logging context in case that has any bearing:

    let level = (process.env.LOG_LEVEL || 'info').toLowerCase();
    let ip = (process.env.NODE_IP || IP.address()).replace(/\./g, '-');
    let options = {
      levels: winston.config.syslog.levels,
      level,
      errorHandler: err => {
        let now = Date.now();
        if ((now - lastFutileAttempt) > 60 * 1000) {
          // Attempt to log this error to cloudwatch if its been more than 60 seconds
          // since the last error.  Even then, delay by 2 seconds....
          lastFutileAttempt = now;
          setTimeout(() => {
            log(logger.WARNING, 'Cloudwatch logging error:', err.message ? err.message : 'unknown');
          }, 2000);
        }
        else if (err) {
          // Content ourselves logging to the console
          console.log('Cloudwatch logging error:', err.message ? err.message : 'unknown');
          console.log(err);
        }
      },
      handleExceptions: true,
      exitOnError: false,
      emitErrs: false,
      awsRegion: config.cloudwatch.region,
      awsOptions: {
        accessKeyId: config.s3.accessKeyId,
        secretAccessKey: config.s3.secretAccessKey,
        // strikes me as odd... don't recall why this is set so; overridden by logStreamName down below
        logStreamName: config.cloudwatch.region
      },
      logGroupName: config.cloudwatch.group_name,
      logStreamName: function() {
        // Spread log streams across dates as the server stays up
        let date = new Date().toISOString().split('T')[0];
        return config.cloudwatch.stream_name + '-' + ip + '-' + date + '-' +
          crypto.createHash('md5').update(startTime).digest('hex');
      }
    };
    logger = new (winston.Logger)({
      levels: winston.config.syslog.levels,
      level,
      handleExceptions: true,
      exitOnError: false,
      emitErrs: false,
      transports: [ new (WinstonCloudWatch)(options) ]
    });

TIA

**Comment by lazywithclass** [comment]
It looks like the code you posted is fine, it shouldn't be getting a 400 "Rate exceeded", is this the only place where you are sending logs to CloudWatch?

I don't think the delay by 2 seconds has any effect on the problem, I think you might as well remove it if you're sure the `if` is working correctly, also, you should be able to send logs much faster than every 60 seconds.

One thing you could do to narrow down the problem is to use the [simulation](https://github.com/lazywithclass/winston-cloudwatch#simulation) tool I've written, it allows you to test your log group / stream, along with some custom code, try to send multiple records. I've just tried and you definitely can.

**Comment by dnewman-polar3d** [comment]
The every 60 seconds should only be in the event of an error (that code being in the errorHandler).  Please correct me if I'm mistaken.

There are certainly other servers logging to CloudWatch: another seven of which a couple log frequently (more than once a second).   And one of those servers logs to the same log group, but a different log stream.  Of the eight total servers, there are seven log groups and eight distinct log streams.

I'll take a look at your simulation tool.  Thanks.

**Comment by lazywithclass** [comment]
I see; make sure that you have a stream for every topic you want to monitor, this is a best practice from AWS, winston-cloudwatch supports the use of a function to determine the name of the stream, this way you could construct the name based on the server, time, whatever you wish.

Have a look at [this example](https://github.com/lazywithclass/winston-cloudwatch/blob/master/examples/function-config.js#L19) for a detailed explanation.
