### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by crucialwebstudio** [lazywithclass/winston-cloudwatch#70]
Hello,

I have this code:

```
const winston = require('winston');
const winstonCloudwatch = require('winston-cloudwatch');

winston.add(new winstonCloudwatch({
    logGroupName: 'testing',
    logStreamName: 'first'
}));

winston.error('1');
```

and I receive this error:

```
/vagrant/convertup/service-mail/node_modules/winston-cloudwatch/index.js:74
    return callback(null, true);
           ^

TypeError: callback is not a function
    at WinstonCloudWatch.log (/vagrant/convertup/service-mail/node_modules/winston-cloudwatch/index.js:74:12)
    at WinstonCloudWatch.TransportStream._write (/vagrant/convertup/service-mail/node_modules/winston-transport/index.js:88:17)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at WinstonCloudWatch.Writable.write (_stream_writable.js:243:11)
    at DerivedLogger.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at DerivedLogger.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at DerivedLogger.Readable.push (_stream_readable.js:134:10)
```

I am using:

```
winston: ^3.0.0-rc0,
winston-cloudwatch: ^1.12.0
node: v6.11.3
```

Caveats:

1. I realize `winston: ^3.0.0-rc0` is ahead of your `winston: ^2.1.1` but wanted to bring it up since Winston 3 will be out eventually.

1. The log groups/streams do not exist and the machine I am running on does not have permission to create them. So I fully expect an error. I'm just trying to understand error handling in general and how to keep my app from crashing in this case.

Caveats aside:
Do you think this is related to Winston 3? or am I doing something else wrong?

Thanks!

**Comment by crucialwebstudio** [comment]
Thanks for your reply and pointing out winston's `uncaughtException` handler. I've updated my code to this:

```
const winston           = require('winston');
const winstonCloudwatch = require('winston-cloudwatch');

winston.add(new winstonCloudwatch({
    logGroupName: 'testing',
    logStreamName: 'first'
}));

// handle uncaught exceptions
winston.exceptions.handle(
    new winston.transports.File({ filename: './log/exceptions.log' })
);

winston.error('1');
```

However, now I am getting nothing in the console, nothing in `./log/exceptions.log` and nothing in cloudwatch (<- this part is expected, as I mentioned)

I guess, to simplify the discussion...

Going back to my original code without the exception handler, how am I getting `TypeError: callback is not a function`?

I think that means I don't have an `uncaughtException` handler, but that is misleading since:

- even then the error should go to `console.error`
- the real error I am expecting is along the lines of `unable to create cloudwatch log group or stream`, or something to that effect

Should `console.error` report the inability to create cloudwatch logs, rather than `TypeError: callback is not a function`?

Thanks!

**Comment by crucialwebstudio** [comment]
Ok, so I downgraded to winston: 2.4.0 and started getting something more like what I expected in the console.

```
{ UnrecognizedClientException: The security token included in the request is invalid.
    at Request.extractError (/vagrant/convertup/service-mail/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/vagrant/convertup/service-mail/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/vagrant/convertup/service-mail/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/vagrant/convertup/service-mail/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/vagrant/convertup/service-mail/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/vagrant/convertup/service-mail/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /vagrant/convertup/service-mail/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/vagrant/convertup/service-mail/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/vagrant/convertup/service-mail/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/vagrant/convertup/service-mail/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The security token included in the request is invalid.',
  code: 'UnrecognizedClientException',
  time: 2017-10-14T18:08:34.209Z,
  requestId: 'b1600a48-b10a-11e7-9cd3-b7a2197ab9b6',
  statusCode: 400,
  retryable: false,
  retryDelay: 66.79119486059494 }
```

I think we can put a pin in this issue and attribute it to incompatibility with `winston ^3.0.0-rc0`.

I'll be happy to revisit this and help you test for winston 3 when you're ready.

**Comment by lazywithclass** [comment]
Yes agreed, let's revisit it by then.

**Comment by aneilbaboo** [comment]
@lazywithclass - ah, thanks for the pointer. That PR works for me.

**Comment by lazywithclass** [comment]
@aneilbaboo great, I'll close this then.
