### ISSUE TITLE
got 404 unknown error

### ISSUE THREAD

**Issue by stephen1706** [lazywithclass/winston-cloudwatch#81]
why does whenever i do a log, i always got 404 unknown error. probably it was triggered when it is going to submit to cloudwatch? 

```
{ UnknownError: Not Found
    at Request.extractError (/Users/stephenadipradhana/Documents/work.nosync/sso-identity-express/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/stephenadipradhana/Documents/work.nosync/sso-identity-express/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/stephenadipradhana/Documents/work.nosync/sso-identity-express/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/stephenadipradhana/Documents/work.nosync/sso-identity-express/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/stephenadipradhana/Documents/work.nosync/sso-identity-express/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/stephenadipradhana/Documents/work.nosync/sso-identity-express/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/stephenadipradhana/Documents/work.nosync/sso-identity-express/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/stephenadipradhana/Documents/work.nosync/sso-identity-express/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/stephenadipradhana/Documents/work.nosync/sso-identity-express/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/stephenadipradhana/Documents/work.nosync/sso-identity-express/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Not Found',
  code: 'UnknownError',
  statusCode: 404,
  time: 2018-03-26T07:02:25.763Z,
  requestId: 'OQKS639BAA0PVLECCD8H11ABM7VV4KQNSO5AEMVJF66Q9ASUAAJG',
  retryable: false,
  retryDelay: 34.44511315179366 }
```

here is my code : 
```

const logger = new winston.Logger({
    transports: [
      new (winston.transports.Console)({
        timestamp: true,
        colorize: true,
      })
    ]
});
const config = {
    logGroupName: 'account-service',
    logStreamName: NODE_ENV,
    createLogGroup: false,
    createLogStream: true,
    awsConfig: {
      accessKeyId: CLOUDWATCH_ACCESS_KEY_ID,
      secretAccessKey: CLOUDWATCH_SECRET_ACCESS_KEY,
      region: region
    },
    formatLog: function (item) {
      return item.level + ': ' + item.message + ' ' + JSON.stringify(item.meta)
    }
};
logger.add(WinstonCloudWatch, config);
logger.info("[REQUEST] /users", {
        tags: 'account,register',
        request: req.body
    });
```

**Comment by lazywithclass** [comment]
I assume `NODE_ENV` is there right? Please make sure about this.

One thing you can do is to use [the simulation tool](https://github.com/lazywithclass/winston-cloudwatch#simulation) I wrote to understand if the problem is in your code or if I have to fix a bug that's preventing you from saving logs.

**Comment by lazywithclass** [comment]
Ok great!
